# Generated by Django 4.2.6 on 2023-11-03 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_rename_image_job_imagefun"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="imagefun",
            new_name="image",
        ),
    ]
